CREATE TABLE MEAL (
  ID INT AUTO_INCREMENT,
  NAME VARCHAR(255),
  PRICE DOUBLE,
  CALORIES INT,
  PRIMARY KEY (ID)
);

INSERT INTO MEAL(NAME, PRICE, CALORIES)
VALUES ('Spaghetti Bolognese', 12.99, 600),
('Grilled Chicken Sandwich', 8.99, 400),
('Pesto Pasta', 10.99, 550),
('Steak and Mash', 19.99, 800),
('Sushi Platter', 15.99, 700);


ALTER TABLE MEAL
MODIFY COLUMN NAME VARCHAR(255) NOT NULL;

ALTER TABLE MEAL
MODIFY COLUMN PRICE INT NOT NULL;

ALTER TABLE MEAL
ADD CONSTRAINT PRICE CHECK (PRICE > 5)

ALTER TABLE MEAL
ADD CONSTRAINT CALORIES CHECK (CALORIES < 1000);
