CREATE TABLE MEAL (
  ID INT AUTO_INCREMENT,
  NAME VARCHAR(255),
  PRICE DOUBLE,
  CALORIES INT,
  PRIMARY KEY (ID)
);

INSERT INTO MEAL(NAME, PRICE, CALORIES)
VALUES ('Spaghetti Bolognese', 12.40, 600),
('Grilled Chicken Sandwich', 8.55, 400),
('Pesto Pasta', 10.20, 550),
('Steak and Mash', 19.80, 800),
('Sushi Platter', 15.35, 700);

1.
SELECT MAX(PRICE) AS MAX_PRICE
FROM MEAL
WHERE CALORIES > 500;

2.
SELECT AVG(CALORIES) AS Average_calories
FROM MEAL
WHERE PRICE > 15;

3.
SELECT PRICE
FROM MEAL
GROUP BY PRICE
HAVING PRICE = (SELECT MAX(PRICE) FROM MEAL);

4.
SELECT PRICE
FROM MEAL
GROUP BY PRICE
HAVING PRICE < (SELECT AVG(PRICE) FROM MEAL)

5.
SELECT PRICE
FROM MEAL
WHERE CALORIES > 600
GROUP BY PRICE
HAVING PRICE < (SELECT AVG(PRICE) FROM MEAL);