SELECT *
FROM MEAL m
LEFT JOIN INGREDIENT i ON m.ID  = i.MEAL_ID

SELECT *
FROM MEAL m
RIGHT JOIN INGREDIENT i ON m.ID  = i.MEAL_ID

SELECT *
FROM MEAL m
RIGHT JOIN INGREDIENT i ON m.ID  = i.MEAL_ID
WHERE i.MEAL_ID = NULL;

SELECT *
FROM MEAL m
INNER JOIN INGREDIENT i ON m.ID  = i.MEAL_ID

SELECT *
FROM MEAL m
INNER JOIN INGREDIENT i ON m.ID  = i.MEAL_ID
where m.ID = null